apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: area-module
  name: area-module
spec:
  ports:
    - name: "3103"
      port: 3103
      targetPort: 3003
  selector:
    io.kompose.service: area-module
