apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: area-module
  name: area-module
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: area-module
  template:
    metadata:
      annotations:
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: area-module
    spec:
      containers:
        - env:
            - name: PORT
              value: "3003"
            - name: QUEUE_NAME
              value: area_queue
            - name: PREFIX
              value: area-module
          image: area-module:latest
          resources:
            requests:
              memory: "50Mi"
              cpu: "2m"
            limits:
              memory: "1024Mi"
              cpu: "50m"
          imagePullPolicy: Never
          name: area-module
          ports:
            - containerPort: 3003
              protocol: TCP
      restartPolicy: Always
