apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\alany\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f ../../docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: auth-module
  name: auth-module
spec:
  ports:
    - name: "3102"
      port: 3102
      targetPort: 3002
  selector:
    io.kompose.service: auth-module
