apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: location-module
  name: location-module
spec:
  ports:
    - name: "3104"
      port: 3104
      targetPort: 3004
  selector:
    io.kompose.service: location-module
