apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: location-module
  name: location-module
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: location-module
  template:
    metadata:
      annotations:
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: location-module
    spec:
      containers:
        - env:
            - name: PORT
              value: "3004"
            - name: QUEUE_NAME
              value: location_queue
            - name: PREFIX
              value: location-module
          image: location-module:latest
          imagePullPolicy: Never
          name: location-module
          ports:
            - containerPort: 3004
              protocol: TCP
      restartPolicy: Always
