apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\alany\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f ../../docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: logging-module
  name: logging-module
spec:
  ports:
    - name: "3105"
      port: 3105
      targetPort: 3005
  selector:
    io.kompose.service: logging-module
